-- REVIEW ONLY — Asri Collection payment baseline draft
-- Reference: read-only audit of legacy asri_payment_* schema and Duitku function contracts.
-- Target: a NEW dedicated Asri Collection Supabase project only.
-- This file intentionally lives in docs/drafts; it is NOT an executable migration yet.
-- Before promotion into supabase/migrations, generate the migration file with Supabase CLI,
-- copy the reviewed SQL, then run local/disposable-database verification.
-- Keep payment tables server-only; do not apply to the legacy shared project.
-- The history ID uses IDENTITY so server inserts can omit it; the audited legacy table
-- had no visible default for this column, which is treated as a baseline defect correction.

create table public.asri_payment_orders (
  id uuid primary key default gen_random_uuid(),
  merchant_order_id text not null unique,
  user_id uuid,
  amount bigint not null,
  currency text not null default 'IDR',
  status text not null default 'pending',
  payment_method text,
  product_details text,
  customer_email text,
  customer_phone text,
  customer_va_name text,
  additional_param text,
  merchant_user_info text,
  callback_url text,
  return_url text,
  expiry_period integer,
  provider text not null default 'duitku',
  provider_reference text,
  payment_url text,
  va_number text,
  qr_string text,
  app_url text,
  provider_status_code text,
  provider_status_message text,
  failure_reason text,
  expires_at timestamptz,
  paid_at timestamptz,
  failed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint asri_payment_orders_amount_check check (amount > 0),
  constraint asri_payment_orders_currency_check check (currency = 'IDR'),
  constraint asri_payment_orders_expiry_period_check check (expiry_period is null or expiry_period > 0),
  constraint asri_payment_orders_status_check check (
    status in ('draft', 'pending', 'paid', 'failed', 'cancelled', 'expired', 'creation_failed')
  )
);

create table public.asri_payment_transactions (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.asri_payment_orders(id) on delete restrict,
  provider text not null default 'duitku',
  provider_reference text,
  payment_code text,
  payment_method text,
  amount bigint not null,
  fee bigint,
  status_code text,
  status_message text,
  publisher_order_id text,
  settlement_date_text text,
  settlement_date timestamptz,
  issuer_code text,
  customer_name text,
  raw_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint asri_payment_transactions_amount_check check (amount > 0),
  constraint asri_payment_transactions_fee_check check (fee is null or fee >= 0)
);

create table public.asri_payment_callbacks (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'duitku',
  merchant_order_id text not null,
  signature text,
  signature_valid boolean not null default false,
  result_code text,
  payment_code text,
  reference text,
  publisher_order_id text,
  sp_user_hash text,
  settlement_date text,
  issuer_code text,
  customer_name text,
  payload jsonb not null,
  processing_status text not null default 'received',
  http_status integer,
  event_fingerprint text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  constraint asri_payment_callbacks_processing_status_check check (
    processing_status in ('received', 'processed', 'rejected', 'failed', 'duplicate')
  )
);

create table public.asri_payment_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.asri_payment_orders(id) on delete restrict,
  previous_status text,
  new_status text not null,
  source text not null,
  provider_status_code text,
  note text,
  created_at timestamptz not null default now(),
  constraint asri_payment_status_history_new_status_check check (
    new_status in ('draft', 'pending', 'paid', 'failed', 'cancelled', 'expired', 'creation_failed')
  ),
  constraint asri_payment_status_history_source_check check (
    source in ('create', 'callback', 'status_check', 'reconciliation', 'admin')
  )
);

create index asri_payment_transactions_order_id_idx
  on public.asri_payment_transactions (order_id);

create unique index asri_payment_transactions_provider_reference_uidx
  on public.asri_payment_transactions (provider, provider_reference)
  where provider_reference is not null;

create index asri_payment_callbacks_order_id_idx
  on public.asri_payment_callbacks (merchant_order_id, received_at desc);

create unique index asri_payment_callbacks_fingerprint_uidx
  on public.asri_payment_callbacks (event_fingerprint)
  where event_fingerprint is not null;

create index asri_payment_status_history_order_id_idx
  on public.asri_payment_status_history (order_id, created_at desc);

alter table public.asri_payment_orders enable row level security;
alter table public.asri_payment_transactions enable row level security;
alter table public.asri_payment_callbacks enable row level security;
alter table public.asri_payment_status_history enable row level security;

revoke all on public.asri_payment_orders from public, anon, authenticated;
revoke all on public.asri_payment_transactions from public, anon, authenticated;
revoke all on public.asri_payment_callbacks from public, anon, authenticated;
revoke all on public.asri_payment_status_history from public, anon, authenticated;

grant all on public.asri_payment_orders to service_role;
grant all on public.asri_payment_transactions to service_role;
grant all on public.asri_payment_callbacks to service_role;
grant all on public.asri_payment_status_history to service_role;
